---
     
name: fmtya
author: norwd
description: "GitHub Action to run yamlfmt"

branding:
  icon: edit
  color: blue

inputs:
  token:
    description: "Used to authenticate with GitHub, this should be a PAT with `repo: write` and `workflow: write` permissions."

  yamlfmt-version:
    default: "latest"
    description: "The specifc version of the yamlfmt tool to use, defaults to the latest vailable version."

  commit-message:
    default: "Auto yamlfmt"
    description: "The message used to commit any changes made by yamlfmt."

  commit-user-name:
    default: "github-actions[bot]"
    description: "Who the commit should be attributed to, defaults to the GitHub Actions bot."

  commit-user-email:
    default: "41898282+github-actions[bot]@users.noreply.github.com"
    description: "Who the commit should be attributed to, defaults to the GitHub Actions bot."

  signing-private-key:
    description: "A GPG private key to sign the commit with. This must be exported as an ASCII armored version or its base64 encoding."

  signing-passphrase:
    description: "The password or passphrase for the signing key, if one was used."

  include-files:
    default: "**/*.{yaml,yml}"
    description: "Which files or file patterns to include in the formatter, one pattern per line. Defaults to all yaml files. The glob paths are implemented using the bmatcuk/doublestar package."

  exclude-files:
    description: "Which files or file patterns to exclude from the formatter, one pattern per line. Glob paths follow the same format as `include-files`."

  indent-size:
    default: 2
    description: "How big to make each indent level."

  include-document-start:
    default: true
    description: "Whether yaml files should begin with `---` at the start."

  line-ending-type:
    default: "lf"
    description: "Determines the type of newline characters to use, must be either `lf` or `crlf`."

  keep-line-breaks:
    default: true
    description: "Keep existing line breaks in formatted yaml."

  disallow-anchors:
    default: false
    description: "Whether to reject any YAML anchors or aliases found in the document."

runs:
  using: composite
  steps:
    - name: "Validate Configuration"
      id: config
      shell: bash
      env:
        YAMLFMT_VERSION: ${{ inputs.yamlfmt-version }}
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
        COMMIT_USER_NAME: ${{ inputs.commit-user-name }}
        COMMIT_USER_EMAIL: ${{ inputs.commit-user-email }}
        INCLUDE_FILES: ${{ inputs.include-files }}
        EXCLUDE_FILES: ${{ inputs.exclude-files }}
        INDENT_SIZE: ${{ inputs.indent-size }}
        INCLUDE_DOC_START: ${{ inputs.include-document-start }}
        LINE_ENDING_TYPE: ${{ inputs.line-ending-type }}
        KEEP_LINE_BREAKS: ${{ inputs.keep-line-breaks }}
        DISALLOW_ANCHORS: ${{ inputs.disallow-anchors }}
      run: |
        die() {
          echo "::error::$@"
          exit 1
        }

        [ -z "$YAMLFMT_VERSION" ] && die "No yamlfmt version provided"
        [ -z "$COMMIT_MESSAGE" ] && die "No commit message provided"
        [ -z "$COMMIT_USER_NAME" ] && die "No commit user name provided"
        [ -z "$COMMIT_USER_EMAIL" ] && die "No commit user email provided"
        [ -z "$INCLUDE_FILES" ] && die "No include files provided"
        [ -z "$INDENT_SIZE" ] && die "No indent size provided"
        [ -z "$INCLUDE_DOC_START" ] && die "No include document start setting provided"
        [ -z "$LINE_ENDING_TYPE" ] && die "No line ending type provided"
        [ -z "$KEEP_LINE_BREAKS" ] && die "No keep line breaks setting provided"
        [ -z "$DISALLOW_ANCHORS" ] && die "No disallow anchors setting provided"

        echo "include-files=$(echo "$INCLUDE_FILES" | jq -R | jq -R | jq -s | jq -r tostring)" >> "$GITHUB_OUTPUT"
        echo "exclude-files=$(echo "$EXCLUDE_FILES" | jq -R | jq -R | jq -s | jq -r tostring)" >> "$GITHUB_OUTPUT"

    - name: "Checkout"
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        token: ${{ inputs.token || github.token }}

    - name: "Setup Go"
      uses: actions/setup-go@v3
      with:
        token: ${{ inputs.token || github.token }}

    - name: "Install yamlfmt"
      shell: bash
      env:
        VERSION: ${{ inputs.yamlfmt-version }}
      run: go install "github.com/google/yamlfmt/cmd/yamlfmt@$VERSION"

    - name: "Configure yamlfmt"
      shell: bash
      run: |
        cat << 'EOF' > ${{ runner.temp }}/yamlfmt.conf
        include:
          - ${{ join(fromJSON(steps.config.outputs.include-files), '
          - ') || '' }}
        exclude:
          - ${{ join(fromJSON(steps.config.outputs.exclude-files), '
          - ') || '' }}
        formatter:
          type: basic
          indent: ${{ inputs.indent-size }}
          include_document_start: ${{ inputs.include-document-start }}
          line_ending: ${{ inputs.line-ending-type }}
          retain_line_breaks: ${{ inputs.keep-line-breaks }}
          disallow_anchors: ${{ inputs.disallow-anchors }}
        EOF

    - name: "Run yamlfmt"
      shell: bash
      run: ~/go/bin/yamlfmt -conf "${{ runner.temp }}/yamlfmt.conf"

    - name: "Setup GPG Keys"
      if: inputs.signing-private-key != ''
      continue-on-error: true
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ inputs.signing-private-key }}
        passphrase: ${{ inputs.signing-passphrase }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: "Commit Changes"
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_user_name: ${{ inputs.commit-user-name }}
        commit_user_email: ${{ inputs.commit-user-email }}
        commit_message: ${{ inputs.commit-message }}
        commit_options: ${{ inputs.signing-private-key != '' && '-S' || '' }}
